### ISSUE TITLE
Problematic copy of metadata in RemovePtrToIntPass

### ISSUE THREAD

**Issue by shaobo-he** [seahorn/sea-dsa#108]
Hello sea-dsa developers,

It seems the copying of metadata in `RemovePtrToIntPass` is problematic. Specifically, `load` instructions can carry `range` metadata (https://llvm.org/docs/LangRef.html#range-metadata). So, if the source of the `inttoptr` instruction is a `load` instruction with such metadata, this pass would generate an invalid `load` instruction since the metadata is intended for an integer type. I have no idea why a compiler would produce such code but rustc does it.

**Comment by agurfinkel** [comment]
Hey @shaobo-he could you submit a PR for this? Or at least provide an example. I think we mostly want to copy over debug info. A solution would be to strip metadata that does not belong on a load after all other metadata was copied. This is hard to get right without a working example...

**Comment by shaobo-he** [comment]
> Hey @shaobo-he could you submit a PR for this? Or at least provide an example. I think we mostly want to copy over debug info. A solution would be to strip metadata that does not belong on a load after all other metadata was copied. This is hard to get right without a working example...

I'll attach an example with instructions to run it.

**Comment by shaobo-he** [comment]
[test.zip](https://github.com/seahorn/sea-dsa/files/5550615/test.zip)

To reproduce (using commit 4d460bb1f0), please try,
```bash
run/bin/seadsa -sea-dsa=ci -sea-dsa-dot test1.bc -oll test2.ll
```
If I run sea-dsa binary again on `test2.ll`, I got,
```llvm
Range types must match instruction type!
  %248 = load %"core::fmt::Formatter"*, %"core::fmt::Formatter"** %247, align 8, !dbg !9660, !range !2499, !noalias !9629
Range types must match instruction type!
  %1413 = load [0 x i8]*, [0 x i8]** %1412, align 8, !dbg !19566, !range !2499, !alias.scope !19567, !noalias !19580
Range types must match instruction type!
  %2088 = load [0 x i8]*, [0 x i8]** %2087, align 8, !dbg !20602, !range !2499, !alias.scope !20603, !noalias !20608
Range types must match instruction type!
  %619 = load [0 x i8]*, [0 x i8]** %618, align 8, !dbg !23804, !range !2499, !alias.scope !23805, !noalias !23810
Range types must match instruction type!
  %772 = load [0 x i8]*, [0 x i8]** %771, align 8, !dbg !25656, !range !2499, !alias.scope !25657, !noalias !25034
Range types must match instruction type!
  %17 = load [0 x i8]*, [0 x i8]** %16, align 8, !dbg !31450, !range !2499, !alias.scope !31457, !noalias !31462
Range types must match instruction type!
  %65 = load [0 x i8]*, [0 x i8]** %64, align 8, !dbg !31548, !range !2499, !alias.scope !31551, !noalias !31556
Range types must match instruction type!
  %113 = load [0 x i8]*, [0 x i8]** %112, align 8, !dbg !31641, !range !2499, !alias.scope !31646, !noalias !31651
Range types must match instruction type!
  %163 = load [0 x i8]*, [0 x i8]** %162, align 8, !dbg !31737, !range !2499, !alias.scope !31742, !noalias !31747
Range types must match instruction type!
  %199 = load [0 x i8]*, [0 x i8]** %198, align 8, !dbg !31820, !range !2499, !alias.scope !31823, !noalias !31828
Range types must match instruction type!
  %25 = load %"path::Path"*, %"path::Path"** %24, align 8, !dbg !44325, !range !2499
Range types must match instruction type!
  %27 = load %"ffi::os_str::OsStr"*, %"ffi::os_str::OsStr"** %26, align 8, !dbg !44325, !range !2499
LLVM ERROR: Broken module found, compilation aborted!
```
