### ISSUE TITLE
Selecting program entry point

### ISSUE THREAD

**Issue by shaobo-he** [seahorn/sea-dsa#126]
Hello sea-dsa developers,

I noticed that the entry point of the program to analyze is supposed to be `main`. For example, the following lines indicate that global variables are only analyzed when `main` is found,

```C
  if (F.getName().equals("main")) {
    GlobalBuilder globalBuilder(F, g, m_dl, tli, m_allocInfo);
    globalBuilder.initGlobalVariables();
  }
```

However, the applications I'm working on don't have `main` as the entry points. So I was wondering if it's possible to add an option like `--entry-point` to select the program entry point.

**Comment by caballa** [comment]
We have in SeaHorn a pass that creates a main and calls all the entry points (given by the user) with nondeterministic inputs.
(https://github.com/seahorn/seahorn/blob/dev10/lib/Transforms/Utils/DummyMainFunction.cc)

Can you do something similar in SMACK?

**Comment by shaobo-he** [comment]
> We have in SeaHorn a pass that creates a main and calls all the entry points (given by the user) with nondeterministic inputs.
> (https://github.com/seahorn/seahorn/blob/dev10/lib/Transforms/Utils/DummyMainFunction.cc)
> 
> Can you do something similar in SMACK?

Yes, I was actually thinking along this direction. It should be doable but maybe non-trivial for my use-cases.

**Comment by shaobo-he** [comment]
@caballa thank you for your reply. Since there has been a solution, I closed this issue.
