### ISSUE TITLE
Constructing paths from memory object to use-pointers

### ISSUE THREAD

**Issue by kayondomartin** [seahorn/sea-dsa#132]
I was wondering whether it's possible to construct paths from a memory object to all its users using this API. If so, I'd appreciate any directions.

Thanks a lot in advance

**Comment by caballa** [comment]
Take a look at https://github.com/seahorn/sea-dsa/blob/dev10/include/seadsa/SeaMemorySSA.hh.
This class puts the program in Memory SSA form using sea-dsa and provides an API to access definitions and users.
