### ISSUE TITLE
Fail to run an example

### ISSUE THREAD

**Issue by XidianGeneral** [seahorn/sea-dsa#34]
I have successfully built seadsa with LLVM-3.8, and got the executable program.
I want to run the example is tests/test-ext-1.ll, but it fails:

```
$ seadsa -dsa-stats test-ext-1.ll 
#0 0x0000000000e868f5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/bin/seadsa+0xe868f5)
#1 0x0000000000e84916 llvm::sys::RunSignalHandlers() (/usr/local/bin/seadsa+0xe84916)
#2 0x0000000000e84b15 SignalHandler(int) (/usr/local/bin/seadsa+0xe84b15)
#3 0x00007ff1f98ec340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#4 0x00000000009ade60 llvm::ValueHandleBase::AddToExistingUseList(llvm::ValueHandleBase**) (/usr/local/bin/seadsa+0x9ade60)
#5 0x000000000068e0f7 llvm::ValueHandleBase::ValueHandleBase(llvm::ValueHandleBase::HandleBaseKind, llvm::ValueHandleBase const&) (/usr/local/bin/seadsa+0x68e0f7)
#6 0x00000000006f732d llvm::WeakVH::WeakVH(llvm::WeakVH const&) (/usr/local/bin/seadsa+0x6f732d)
#7 0x00000000006ff58b std::pair<llvm::WeakVH, llvm::CallGraphNode*>::pair(std::pair<llvm::WeakVH, llvm::CallGraphNode*> const&) (/usr/local/bin/seadsa+0x6ff58b)
#8 0x00000000006ff5c9 llvm::mapped_iterator<__gnu_cxx::__normal_iterator<std::pair<llvm::WeakVH, llvm::CallGraphNode*>*, std::vector<std::pair<llvm::WeakVH, llvm::CallGraphNode*>, std::allocator<std::pair<llvm::WeakVH, llvm::CallGraphNode*> > > >, std::pointer_to_unary_function<std::pair<llvm::WeakVH, llvm::CallGraphNode*>, llvm::CallGraphNode*> >::operator*() const (/usr/local/bin/seadsa+0x6ff5c9)
#9 0x00000000006fdbb1 llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> >::DFSVisitChildren() (/usr/local/bin/seadsa+0x6fdbb1)
#10 0x00000000006faeb3 llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> >::GetNextSCC() (/usr/local/bin/seadsa+0x6faeb3)
#11 0x00000000006fd709 llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> >::scc_iterator(llvm::CallGraphNode*) (/usr/local/bin/seadsa+0x6fd709)
#12 0x00000000006fab8b llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> >::begin(llvm::CallGraph* const&) (/usr/local/bin/seadsa+0x6fab8b)
#13 0x00000000006f84f8 llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> > llvm::scc_begin<llvm::CallGraph*>(llvm::CallGraph* const&) (/usr/local/bin/seadsa+0x6f84f8)
#14 0x00000000007068ec sea_dsa::BottomUpAnalysis::runOnModule(llvm::Module&, llvm::DenseMap<llvm::Function const*, std::shared_ptr<sea_dsa::Graph>, llvm::DenseMapInfo<llvm::Function const*>, llvm::detail::DenseMapPair<llvm::Function const*, std::shared_ptr<sea_dsa::Graph> > >&) (/usr/local/bin/seadsa+0x7068ec)
#15 0x00000000006f5411 sea_dsa::ContextSensitiveGlobalAnalysis::runOnModule(llvm::Module&) (/usr/local/bin/seadsa+0x6f5411)
#16 0x00000000006e6074 sea_dsa::DsaAnalysis::runOnModule(llvm::Module&) (/usr/local/bin/seadsa+0x6e6074)
#17 0x0000000000990fa0 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/bin/seadsa+0x990fa0)
#18 0x000000000068ce04 main (/usr/local/bin/seadsa+0x68ce04)
#19 0x00007ff1f8d18ec5 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec5)
#20 0x000000000068bf6c _start (/usr/local/bin/seadsa+0x68bf6c)
Stack dump:
0.	Program arguments: seadsa -dsa-stats test-ext-1.ll 
1.	Running pass 'SeaHorn Dsa analysis: entry point for all Dsa clients' on module 'test-ext-1.ll'.
Segmentation fault (core dumped)
```

How to solve it?

By the way, can sea-dsa analyze the LLVM bytecode of a Linux kernel driver?
I want to use sea-dsa to print the function referenced by a function pointer in the driver code. Can sea-dsa do it?

Thanks in advance!

**Comment by XidianGeneral** [comment]
Thanks for your reply :)

I download the source code, and input the commands:
$ mkdir build; cd build/
$ cmake ../
$ make -j4
But I get the same errors of #33 .

I solve it by adding "SET(CMAKE_CXX_FLAGS "-fno-rtti")" in src/CMakeLists.txt, tests/CMakeLists.txt, tools/CMakeLists.txt and units/CMakeLists.txt.

Then I input the commands again:
$ cmake ../
$ make -j4
$ sudo make install

The code is successfully compiled, and I get the program in build/tools/seadsa and install it.
Then I run this program in tests/:
$ seadsa -dsa-stats test-ext-1.ll

Finally, I get the errors...

I am a little suprised that sea-dsa cannot handle function pointers.
So I want to have a try of using SeaHorn to handle function pointers in Linux drivers, so is the code available in this link?
https://github.com/seahorn/seahorn

By the way, I remember DSA can handle function pointers.
I also want to run DSA, but it is disappointing that it has been removed from LLVM mainline...
Have you actually run it? Could you please show me some helpful material or links?

Thanks in advance :)

**Comment by agurfinkel** [comment]
It seems that `sea-dsa` relies on rtti which is not enabled by default in LLVM.
I do not know why `sea-dsa` depends on rtti, but we always use it with `seahorn` that
does enable `rtti`. 

It might be easiest for you to use `sea-dsa` as part of `seahorn` instead of compiling it on its own.
There are instructions in `CMakeLists.txt` to compile LLVM properly.

Handling function pointers is unfortunately a missing feature. It is present in DSA, but since we did not need it, we haven't reimplemented it in `sea-dsa`. It is something that should not be hard to do in principle, but it is not trivial. We might implement it in the future, and/or would be happy to help you should you choose to do it yourself.

We maintain a port of the original dsa. It is also used in seahorn. The repo is here: https://github.com/seahorn/llvm-dsa . As with `sea-dsa`, it should be possible to compile
it by itself, but we only use it with seahorn and might have introduced some extra dependencies
on our compilation flags. Be warned that `llvm-dsa` is rather buggy. We will not fix any bugs in it.
The difficulty of working with it is that what lead us to implement `sea-dsa` to replace it.

**Comment by agurfinkel** [comment]
To try seahorn, you might want to checkout our docker distribution.
