### ISSUE TITLE
Port to LLVM 5.0

### ISSUE THREAD

**Issue by caballa** [seahorn/sea-dsa#35]
- [x] ported code in branch llvm-5.0
- [x] pass all tests
- [x] Update .travis to download llvm/clang 5.0

**Comment by agurfinkel** [comment]
travis does not download clang. It uses a pre-build docker machine
We should be able to rebuild a machine using scripts in `docker` and tag it appropriately on docker.hub
travis.yml then needs to be updated to grab the right docker machine
