### ISSUE TITLE
empty labels in the complete call graph

### ISSUE THREAD

**Issue by BushraAloraini** [seahorn/sea-dsa#51]
Hi all, I using the sea-dsa analysis framework as a library and it works fine. I came across an issue where when printing CompleteCallGraph into a dot format, it creates empty labels. This does not seem to be the case in the given examples in the "tests/expected_graphs" directory.  I am using MacOs and LLVM 8 to run the analysis. Is this problem related to this settings?

**Comment by caballa** [comment]
The llvm-8.0 branch might not be updated. Can you send me  a test and full command?

**Comment by BushraAloraini** [comment]
Here are the files attached, I run it after building with `cg file.ll`
 
[sea-dsa-issue.zip](https://github.com/seahorn/sea-dsa/files/3748757/sea-dsa-issue.zip)


Thank you so much!

**Comment by caballa** [comment]
I see that you have written your own executable that calls sea-dsa. 
If  I run `seadsa -sea-dsa-callgraph-do test.ll` then the dot file is generated correctly.
I cannot see anything clearly wrong in your code. It might happen that the LLVM values lose their names before the sea-dsa code is called. But for that I will need to compile and install your application.

**Comment by BushraAloraini** [comment]
So even when creating a pass it has similar behaviour. When dumping call graph to stdout it preserves the labels and there are no issues at all with other types of analysis. I have attached the files again including the sea-dsa lib. To build and  run the code
 
cd build
 cmake ..
 make -j4
 ./cg ../test/test.ll 


[sea-dsa-issue.zip](https://github.com/seahorn/sea-dsa/files/3751802/sea-dsa-issue.zip)

Thank you so much!

**Comment by caballa** [comment]
I updated the branch `llvm-8.0`. Since you are building your application using LLVM 8.0 make sure you switch to `llvm-8.0`.

**Comment by BushraAloraini** [comment]
> I updated the branch `llvm-8.0`. Since you are building your application using LLVM 8.0 make sure you switch to `llvm-8.0`.

The problem is solved. Thanks!
