### ISSUE TITLE
Handling of programs compiled with higher optimization levels

### ISSUE THREAD

**Issue by shaobo-he** [seahorn/sea-dsa#53]
Hello SeaDsa developers,

I attempted to use SeaDsa (the llvm-8.0 branch) on a program that I compiled with `-O1` and the resulting graphs seem spurious. For example,

```C
#include <assert.h> 

int* A;

typedef struct {
  int* a;
  long b;
} S;

S* foo() {
  S* x = (S*)malloc(sizeof(S));
  x->a = A;
  assert(1);
  return x;
}

int main() {
  int a = 1;
  A = &a;
  S* y = foo();
  assert(*(y->a) == 1);
  return 0;
}
```
The graph is obtained using the following commands
```bash
clang -O1 -c -emit-llvm -S test1.c
~/sea-dsa/build/run/bin/seadsa -sea-dsa=butd-cs -sea-dsa-type-aware -sea-dsa-dot test1.ll  -sea-dsa-dot-outdir=test1
(cd test1 ; dot -Tpdf main.mem.dot -o main.mem.pdf)
```
[main.mem.pdf](https://github.com/seahorn/sea-dsa/files/3821901/main.mem.pdf)

If I understand it correctly, `*A`, `%1`, and `%5` in the main function should point to the same memory object whereas they are not in the graph.

If I compile the file using O0, then the graph generated seems correct as `*A` and the GEPed pointer returned from `foo` both points to the same object.
[main.mem.pdf](https://github.com/seahorn/sea-dsa/files/3821943/main.mem.pdf)

Please let me know if you can reproduce it or this is expected.

**Comment by shaobo-he** [comment]
@caballa @agurfinkel may I ask if there are any updates on this issue?

**Comment by agurfinkel** [comment]
Not yet. Looks like it fell through the cracks.

The source of the error is that LLVM optimizes a pointer operation into an integer operation. SeaDsa does not track pointers that are stored into integers and misses this case.

We think that the best solution is a pass to fix LLVM IR into an equivalent one that does not convert pointers to integers.

Unfortunately, cycles are low and it might take a little longer than usual to attempt to fix this.
If you feel comfortable with writing LLVM passes, perhaps you can implement and contribute the 
transformation. If you are interested, I'll supply additional details.

**Comment by kuhar** [comment]
@shaobo-he This might be obvious, but also note that SeaDsa/Horn have their own optimization pipelines tuned specifically for program analysis that avoid some transformations (e.g., introducing int2ptr instructions). If possible, it's best to use the this custom preprocessing instead of using the vanilla clang optimizations.

**Comment by shaobo-he** [comment]
Hello everyone,

I found an example in SMACK's regressions that demonstrates this issue even with O0. Consider the following program,

```C
#include <stdbool.h>

#define CAS(x, y, z) __atomic_compare_exchange_n(x, &(y), z, true, 0, 0)

extern void __VERIFIER_assert(bool);

int main(void) {
  int *x = 0;
  int y = 0;
  int *z = x;
  CAS(&z, x, &y); // if (z == x) z = &y;
  __VERIFIER_assert(*z == y);
  return 0;
}
```

The attached graph is obtained using the following commands,
```bash
clang-8 -O0 -c -emit-llvm -S -Xclang -disable-O0-optnone atomic_cas.c
opt-8 atomic_cas.ll -mem2reg -S -o atomic_cas.ll
seadsa -sea-dsa=ci -sea-dsa-type-aware -sea-dsa-dot atomic_cas.ll
dot -Tpdf main.mem.dot -o main.mem.pdf
```
[main.mem.pdf](https://github.com/seahorn/sea-dsa/files/4223142/main.mem.pdf)

The cell `%3` points to should point to the cell `%2` points to according to the semantics of the program. If I describe it accurately, the reason for this bug could be bitcasting pointers like the example above. Could it also be that `cmpxchg` instructions are not supported?

**Comment by kuhar** [comment]
Thanks for the interesting example. I just checked and clang emits the `cmpxchg` llvm instructions which we don't handle at the moment: https://godbolt.org/z/SQYJkM.
It should be pretty straightforward to support it, though -- the handling would be very close to `insertvalue` which we already have code for: https://github.com/seahorn/sea-dsa/blob/55b29333e6661d15fa4d9f69b7e39b80c8f3b5b5/src/DsaLocal.cc#L796.

**Comment by kuhar** [comment]
Ah, the semantics of `cmpxchg` are a bit different than I though:
> The ‘cmpxchg’ instruction is used to atomically modify memory. It loads a value in memory and compares it to a given value. If they are equal, it tries to store a new value into the memory.

> The contents of memory at the location specified by the ‘<pointer>’ operand is read and compared to ‘<cmp>’; if the values are equal, ‘<new>’ is written to the location. The original value at the location is returned, together with a flag indicating success (true) or failure (false).

> The type of ‘<cmp>’ must be an integer or pointer type.

So basically we have to assume that the `<new>` operand (operand 2) may be stored into the pointer abstract object corresponding to `<pointer>`, and that either the `<old>` or `<new>` was returned. The result can be a pointer too. Or as a rewrite in llvm:

```
%res = cmpxchg i64** %pointer, i64* %old, i64* %new
==>
store i64* new, i64** %pointer
%tmp = insertvalue {i1, i64*} undef, %nd, 0
%sel = select i1 %nd, i64* %old, i64* %new
%res = insertvalue {i1, i64*} %tmp, i64* sel, 1
```

**Comment by caballa** [comment]
@shaobo-he : thanks for reporting this. I'll commit something soon. 
I'll implement also `atomicrmw` instruction. 

Given `Res = cmpxchg Ptr, Cmp, New`, the semantics is:
```
OldVal := *Ptr;
if (OldVal == Cmp) 
    *Ptr := New
Res = OldVal
```
The only doubt I have is that llvm-dsa unifies `Res`, `OldVal`, and `Cmp`
https://github.com/seahorn/llvm-dsa/blob/master/lib/DSA/Local.cpp#L475
but I don't see why it needs to be unified with `Cmp`.

**Comment by zvonimir** [comment]
Thanks @caballa! Related to your comment, I have no explanation for why you would be merging with `Cmp` as well. That seems wrong to me, and what you wrote seems reasonable and makes sense.

**Comment by zvonimir** [comment]
Coming back to this since we are still have a problem here, which is it seems related to the original question. In particular, for the example C program, this is the LLVM IR code that gets generated:
```
  %6 = bitcast i32** %3 to i64*, !dbg !39, !verifier.code !30
  %7 = bitcast i32** %1 to i64*, !dbg !39, !verifier.code !30
  %8 = bitcast i32** %4 to i64*, !dbg !39, !verifier.code !30
  %9 = load i64, i64* %7, align 8, !dbg !39, !verifier.code !30
  %10 = load i64, i64* %8, align 8, !dbg !39, !verifier.code !30
  %11 = cmpxchg weak i64* %6, i64 %9, i64 %10 monotonic monotonic, !dbg !39, !verifier.code !30
```
As you can see, clang emits code that stores pointers as i64 integers in this case, which throws off SeaDSA when it hits cmpxchg. Now, if you look at the signature of `cmpxchg`, its second and third argument are of a primitive type, and so I am not sure how we would be able to write an LLVM pass that gets rid of this pattern.

Thoughts?

**Comment by caballa** [comment]
We need to implement something like what we discussed here:

https://github.com/seahorn/sea-dsa/issues/53#issuecomment-583173154

**Comment by caballa** [comment]
How is `%11` used later in the program?

**Comment by shaobo-he** [comment]
> How is `%11` used later in the program?

This is the subsequent part of the program,
```llvm
  %12 = extractvalue { i64, i1 } %11, 0, !dbg !39, !verifier.code !30
  %13 = extractvalue { i64, i1 } %11, 1, !dbg !39, !verifier.code !30
  br i1 %13, label %15, label %14, !dbg !39, !verifier.code !30

; <label>:14:                                     ; preds = %0
  store i64 %12, i64* %7, align 8, !dbg !39, !verifier.code !30
  br label %15, !dbg !39, !verifier.code !30

; <label>:15:                                     ; preds = %14, %0
  br label %16, !dbg !40, !verifier.code !30

; <label>:16:                                     ; preds = %15
  %17 = load i32*, i32** %3, align 8, !dbg !41, !verifier.code !30
  %18 = load i32, i32* %17, align 4, !dbg !41, !verifier.code !30
  %19 = load i32, i32* %2, align 4, !dbg !41, !verifier.code !30
  %20 = icmp eq i32 %18, %19, !dbg !41, !verifier.code !30
  br i1 %20, label %22, label %21, !dbg !44, !verifier.code !30

; <label>:21:                                     ; preds = %16
  call void @__VERIFIER_assert(i32 0), !dbg !41, !verifier.code !45
  br label %22, !dbg !41, !verifier.code !30
```

**Comment by agurfinkel** [comment]
looks like the original issue has been addressed and the new issue does not have a complete repro. I will close this one. @shaobo-he @zvonimir please open a new issue with the example that does not work. Access to bitcode would be appreciated.
