### ISSUE TITLE
Assertion failing in AllocSiteInfo.cc

### ISSUE THREAD

**Issue by igcontreras** [seahorn/sea-dsa#56]
Instructions of this form:
```
%239 = tail call i8* @malloc(i64 0) #7, !dbg !6247
```
cause [this assertion](https://github.com/seahorn/sea-dsa/blob/659e6d9f0fcaf0ee2fc69cf538710e7b7feb03b5/src/AllocSiteInfo.cc#L84) to fail.

**Comment by agurfinkel** [comment]
This is a bug. Can you change the assert to be `>=`?

**Comment by igcontreras** [comment]
Done in https://github.com/seahorn/sea-dsa/pull/57

**Comment by igcontreras** [comment]
Commit c301addc1328e4767654a4f02e72ed09ad0bb84c
