### ISSUE TITLE
Does every pointer value have a cell/node associated with it?

### ISSUE THREAD

**Issue by zvonimir** [seahorn/sea-dsa#68]
To me it seems that when SeaDSA finishes, all pointer values in a program should have a cell/node associated with them. Unless, of course, there are bugs in SeaDSA.
Is that right or am I missing something?
Thanks!

**Comment by agurfinkel** [comment]
Yes. 

At first, SeaDSA runs over every pointer producing instruction and allocates a node for it and a associates a cell with the instruction. 

After that, the nodes are propagated and merged and moved between different functions (in context sensitive version).

**Comment by zvonimir** [comment]
Thanks! Makes sense.
