### ISSUE TITLE
Print the dot file for a graph

### ISSUE THREAD

**Issue by shaobo-he** [seahorn/sea-dsa#69]
Hello sea-dsa developers,

I'd like to print the dot file for a graph in an internal pass of SMACK. It seems that the only proper API to do this is `createDsaPrinterPass`. Using this function requires the pass manager to be available, which I don't know how to get within an LLVM pass. So I was wondering if you could share some pointers about how I should proceed. I think that declaring the pass `createDsaPrinterPass` returns in a header file should work.

**Comment by caballa** [comment]
Just need to follow what we do for method `viewGraph` (https://github.com/seahorn/sea-dsa/blob/master/include/sea_dsa/Graph.hh#L267) 
Add a new method in class `Graph` that does exactly the same that `viewGraph` but without launching the viewer. 
Note that the actual implementation of `viewGraph` is actually defined in https://github.com/seahorn/sea-dsa/blob/master/src/DsaPrinter.cc#L750 .

**Comment by shaobo-he** [comment]
> Just need to follow what we do for method `viewGraph` (https://github.com/seahorn/sea-dsa/blob/master/include/sea_dsa/Graph.hh#L267)
> Add a new method in class `Graph` that does exactly the same that `viewGraph` but without launching the viewer.
> Note that the actual implementation of `viewGraph` is actually defined in https://github.com/seahorn/sea-dsa/blob/master/src/DsaPrinter.cc#L750 .

Thank you for your reply. Should I submit a PR for this since it requires modification in the `Graph` class?

**Comment by caballa** [comment]
Yes, please.

**Comment by shaobo-he** [comment]
Closes via 855c78b.
