### ISSUE TITLE
Sea-Dsa specs compilation does not work on a mac

### ISSUE THREAD

**Issue by agurfinkel** [seahorn/sea-dsa#90]
Mac uses AppleClang and requires special switches to compile C code. 
The current recipe in `tools/CMakeLists.txt` embeds Linux specific compilation options and fails on other architectures.

CMake already knows what are the right switches. It should be used to set the compilation command

**Comment by AVassilev98** [comment]
https://github.com/seahorn/sea-dsa/pull/91
