### ISSUE TITLE
Imprecise call graph

### ISSUE THREAD

**Issue by shaobo-he** [seahorn/sea-dsa#93]
Hello sea-dsa developers,

I used the dev10 branch to produce the call graph for the following program. I think it appears incorrect since `main` should call either one of the two functions indirectly.

```C
int __incr(int x) { return ++x; }

int __decr(int x) { return --x; }

#ifdef __MACH__
int (*incr)(int) = __incr;
int (*decr)(int) = __decr;
#else
int incr(int) __attribute__((alias("__incr")));
int decr(int) __attribute__((alias("__decr")));
#endif

int main(void) {
  int (*fp)(int);
  int x = 1, y = 1;

  if (y > 0) {
    fp = incr;
  } else {
    fp = decr;
  }
  x = fp(x);

  return (x == 2);
}
```

To reproduce, please use the following commands,

```bash
clang func_ptr_alias1.c -c -emit-llvm -S
seadsa --sea-dsa-callgraph-dot func_ptr_alias1.ll
```

This is the call graph I got,

[callgraph.pdf](https://github.com/seahorn/sea-dsa/files/5093289/callgraph.pdf)

**Comment by agurfinkel** [comment]
Can you double check that you are running latest version of everything. I get correct call graph following exact same commands as you do. I am on OSX using AppleClang for `clang`. Perhaps you can include the bitcode file since your compiler might be treating the code differently from mine.

**Comment by shaobo-he** [comment]
> Can you double check that you are running latest version of everything. I get correct call graph following exact same commands as you do. I am on OSX using AppleClang for `clang`. Perhaps you can include the bitcode file since your compiler might be treating the code differently from mine.

Yes, I'm using commit 584fd4d69f4e28b5639f9ff33fcd11e9b0a1dfc5 on a Ubuntu VM. Please see the attached LLVM IR file.

[func_ptr_alias1.txt](https://github.com/seahorn/sea-dsa/files/5093422/func_ptr_alias1.txt)

**Comment by agurfinkel** [comment]
Seems like we don't handle global aliases correctly. On my mac, the globals are converted to a regular assignment. 

as a work-around, please remove the alias attribute

**Comment by caballa** [comment]
Same for me. On OSX it works fine. 
On Ubuntu, it works only without the alias attribute.

**Comment by caballa** [comment]
@shaobo-he : I've committed a fix to resolve calls through aliases. Let me know if you still have problems.

**Comment by shaobo-he** [comment]
> @shaobo-he : I've committed a fix to resolve calls through aliases. Let me know if you still have problems.

Thank you, @caballa. It has been resolved. Closed this issue.
