### ISSUE TITLE
Imprecise call graph

### ISSUE THREAD

**Issue by shaobo-he** [seahorn/sea-dsa#97]
Hello sea-dsa developers,

sea-dsa of `dev10` branch appears to generate an imprecise call graph for the attached C file. Specifically, `parse_input` should call at least `c1`. But the call graph produced and attached only shows that it calls `strcmp`.

To reproduce the call graph, please use the following commands,

```bash
clang -c -emit-llvm -S bftpd_2.i
seadsa --sea-dsa-callgraph-dot bftpd_2.ll
dot -Tpdf callgraph.dotdot -o callgraph.pdf
```
[bftpd_2.txt](https://github.com/seahorn/sea-dsa/files/5115109/bftpd_2.txt)
[callgraph.pdf](https://github.com/seahorn/sea-dsa/files/5115110/callgraph.pdf)

**Comment by caballa** [comment]
Thanks again for sending a simple example to debug.
I've committed a fix in `dev10`.

**Comment by shaobo-he** [comment]
Thank you for the fix, @caballa.

Closed this issue.
